name: lakely
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^9.2.2
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.14
  drift: ^2.23.0
  drift_flutter: ^0.2.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
#  flutter_mobx: ^2.3.0
  flutter_bloc: ^8.1.6
#  flutter_riverpod: ^2.6.1
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.4
#  flutter_quill: ^2.0.7
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.16
  gif: ^2.3.0
  google_fonts: ^6.2.1
  image: ^4.5.2
  installed_apps: ^1.5.2
  intl: ^0.20.1
  json_serializable: ^6.9.0
#  mobx: ^2.5.0
#  mobx_codegen: ^2.7.0
#  riverpod_annotation: ^2.6.1
  objectbox: ^4.0.3
  objectbox_flutter_libs: any
  path_provider: ^2.1.5
  reorderable_grid_view: ^2.2.8
  table_calendar: ^3.2.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.23.0
  objectbox_generator: any
#  riverpod_generator: ^2.6.3
#  custom_lint: ^0.7.0
#  riverpod_lint: ^2.6.3


flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: "launcher_icon"
  image_path_android: "assets/icon/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/foreground.png"
  adaptive_icon_foreground_inset: 0
#   adaptive_icon_monochrome: "assets/icon/monochrome.png"

  ios: true
  image_path_ios: "assets/icon/icon.png"
  remove_alpha_channel_ios: true
  # image_path_ios_dark_transparent: "assets/icon/icon_dark.png"
  # image_path_ios_tinted_grayscale: "assets/icon/icon_tinted.png"
  # desaturate_tinted_to_grayscale_ios: true

  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#000000"
    theme_color: "#000000"

  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48

  macos:
    generate: true
    image_path: "assets/icon/icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/icon.png