name: lakely
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^9.2.2
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.14
  drift: ^2.23.0
  drift_flutter: ^0.2.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
#  flutter_mobx: ^2.3.0
  flutter_bloc: ^8.1.6
#  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.16
  gif: ^2.3.0
  google_fonts: ^6.2.1
  installed_apps: ^1.5.2
  intl: ^0.20.1
  json_serializable: ^6.9.0
#  mobx: ^2.5.0
#  mobx_codegen: ^2.7.0
#  riverpod_annotation: ^2.6.1
  objectbox: ^4.0.3
  objectbox_flutter_libs: any
  path_provider: ^2.1.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.23.0
  objectbox_generator: any
#  riverpod_generator: ^2.6.3
#  custom_lint: ^0.7.0
#  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
